spring:
  application:
    name: Agent-Service
  main:
    web-application-type: reactive


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

server:
  port: 0

#Actuator and circuit breaker
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  #Tracing
  tracing:
    sampling:
      probability: 1.0
