spring:
  application:
    name: Authentication
  main:
    web-application-type: reactive

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

#Tracing
management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 0

keycloak:
  url: http://keycloak:8080/realms/safari/protocol/openid-connect/token
  client:
    id: fairflow
    secret: 3thEeC87gO1MhtT9vSAhY9vV2mV2oEY7