spring:
  application:
    name: Api-Gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: Product-Service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
        - id: Agent-Service
          uri: lb://AGENT-SERVICE
          predicates:
            - Path=/api/agents/**
        - id: Service-Discovery
          uri: http://eureka:password@localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: Service-Discovery-Static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

server:
  port: 8081
