spring:
  application:
    name: Api-Gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: Authentication
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/api/auth/**

        - id: Agent-Service
          uri: lb://AGENT-SERVICE
          predicates:
            - Path=/api/agents/**

        - id: User-Service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: Service-Discovery
          uri: http://eureka:password@service-discovery:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: Service-Discovery-Static
          uri: http://service-discovery:8761
          predicates:
            - Path=/eureka/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8080/realms/safari/protocol/openid-connect/certs"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@service-discovery:8761/eureka

server:
  port: 8181
