version: '3'
services:
  service-discovery:
    build:
      context: ./Service Discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  authentication-service:
    build:
      context: ./Authentication
      dockerfile: Dockerfile
    ports:
      - target: 0
        published: 0
    networks:
      - fair-flow-net
    depends_on:
      - service-discovery

  user-service:
    build:
      context: ./User-Service
      dockerfile: Dockerfile
    ports:
      - target: 0
        published: 0
    networks:
      - fair-flow-net
    depends_on:
      - service-discovery

  api-gateway:
    build:
      context: ./Api Gateway
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    networks:
      - fair-flow-net
    depends_on:
      - service-discovery

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: pdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:20.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/pdb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    ports:
      - 9090:8080
    command:
      - start-dev
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    networks:
      - fair-flow-net

volumes:
  postgres_data:
  keycloak_data:

networks:
  fair-flow-net:
    driver: bridge
