spring:
  application:
    name: Fairflow-App

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

#Tracing
management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 0


datasource:
  url: jdbc:postgresql://postgres-app:5433/fairflow
  username: admin
  password: 1234
  driver-class-name: org.postgresql.Driver

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
