spring:
  application:
    name: Fairflow-App
  datasource:
    url: jdbc:postgresql://postgres-app:5433/fairflow
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

#Tracing
management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 9999

