spring:
  application:
    name: User-Service
  main:
    web-application-type: reactive

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

#Tracing
management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 0

keycloak:
  url: http://localhost:8080
  client:
    id: fairflow
    secret: SqqoTyrdOH1tKD8EsZ2mSjwV9DxDhLcX
  username: admin123
  password: admin
  realm: safari
