spring:
  application:
    name: User-Service
  main:
    web-application-type: reactive

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 0

keycloak:
  url: http://localhost:8080
  client:
    id: fairflow
    secret: WVzvKQ3CNgbZCLEmHNOloO5KKWb2XbRB
  username: admin
  password: admin
  realm: safari

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      validate-group-membership: false
      group:
        liveliness:
          include: diskSpace, db, ping
  probes:
    enabled: true

tracing:
  url: http://localhost:4317
