spring:
  application:
    name: Product-Service
#  main:
#    web-application-type: reactive


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Tracing
management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8083
